common:
  plugin_dir: vendor/plugins/post_pipelines
  rnaseq_dir: /proj/hoodlab/share/vcassen/rna-seq
  script_dir: /proj/hoodlab/share/vcassen/rna-seq/rna-seq-scripts
  genomes_dir: /jdrf/data_var/solexa/genomes
  bin_dir: /hpc/bin

  rnaseq_pipeline: rnaseq_pipeline.rb
#  rnaseq_pipeline: no_op.rb
  tc_script: process_solexa.pl

# These are found in script_dir (above)
  entry_template: entry.template
  launch_template: launch.template
  qsub_template: qsub.template
  no_op_template: no_op.qsub

  fasta_format: faq
  bowtie_opts: -k 11 -m 10 -t --best -q
  bowtie_output_suffix: bowtie.out
  rds_args:  -index -cache 1000 -rawreadID

  ruby: /hpc/bin/ruby
#  ruby: /tools/bin/ruby
  perl: /hpc/bin/perl
  python: /hpc/bin/python
  qsub: /sge/bin/lx24-amd64/qsub
  qsub_opts: -S /bin/sh
#  qsub: /bin/sh

  post_to_slimseq: post_to_slimseq.pl
  export2fasta: fq_all2std.pl
  blat: /package/genome/bin/blat
  blat_opts:
  gather_stats: gather_stats.pl

#  rna_seq_template: no_op.rb
  
  rnaseq_pipelines_enabled: true
